kind: Namespace
apiVersion: v1
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-storage
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-storage
  namespace: openshift-storage
spec:
  targetNamespaces:
    - openshift-storage
