kind: Namespace
apiVersion: v1
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-storage
---
kind: Namespace
apiVersion: v1
metadata:
  name: openshift-cnv
---
kind: Namespace
apiVersion: v1
metadata:
  name: open-cluster-management
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-metering
  labels:
    openshift.io/cluster-monitoring: "true"
---
kind: Namespace
apiVersion: v1
metadata:
  name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators
