apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-build
  namespace: argocd
spec:
  description: Lab Cluster
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-storage
  namespace: argocd
spec:
  destination:
    namespace: openshift-storage
    server: 'https://kubernetes.default.svc'
  project: cluster-build
  source:
    path: storage/local-storage
    repoURL: https://github.com/h00pz/ocp-build.git
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocs
  namespace: argocd
spec:
  destination:
    namespace: openshift-storage
    server: 'https://kubernetes.default.svc'
  project: cluster-build
  source:
    path: storage/ocs
    repoURL: https://github.com/h00pz/ocp-build.git
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnv
  namespace: argocd
spec:
  destination:
    namespace: openshift-cnv
    server: 'https://kubernetes.default.svc'
  project: cluster-build
  source:
    path: cnv
    repoURL: https://github.com/h00pz/ocp-build.git
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm
  namespace: argocd
spec:
  destination:
    namespace: open-cluster-management
    server: 'https://kubernetes.default.svc'
  project: cluster-build
  source:
    path: acm
    repoURL: https://github.com/h00pz/ocp-build.git
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metering
  namespace: argocd
spec:
  destination:
    namespace: openshift-meteringt
    server: 'https://kubernetes.default.svc'
  project: cluster-build
  source:
    path: metering
    repoURL: https://github.com/h00pz/ocp-build.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
