---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: nad-vlan22
  namespace: openshift-cnv
spec:
  config: >-
    {"name":"nad-vlan22","type":"cnv-bridge","cniVersion":"0.3.1","bridge":"br-cnv","vlan":22,"macspoofchk":true,"ipam":{}}
