---
- name: copy files 
  copy:
    src: "{{ item }}"
    dest: /root/
    mode: 0644
  with_items:
    - 1_argo_env.yaml
    - 2_argocd.yaml
    - 3_ns.yaml
    - 4_argocd_cluster_admin.yaml
    - 5_permissions.yaml
    - 6_project.yaml
  when: "'ocp-mgmt' in group_names"

- name: setup ArgoCD env
  command: oc apply -f /root/1_argo_env.yaml
  when: "'ocp-mgmt' in group_names"

- name: setup ArgoCD  
  command: oc apply -f /root/2_argocd.yaml
  when: "'ocp-mgmt' in group_names"
 
- name: setup namespaces
  command: oc apply -f /root/3_ns.yaml
  when: "'ocp-mgmt' in group_names"

- name: setup ArgoCD cluster admin
  command: oc create  -f /root/4_argocd_cluster_admin.yaml
  when: "'ocp-mgmt' in group_names"

- name: setup ArgoCD RoleBindings
  command: oc apply -f /root/4_permissions.yaml
  when: "'ocp-mgmt' in group_names"

- name: setup ArgoCD project
  command: oc apply -f /root/5_project.yaml
  when: "'ocp-mgmt' in group_names"
