apiVersion: v1
items:
- apiVersion: imageregistry.operator.openshift.io/v1
  kind: Config
  metadata:
    creationTimestamp: "2020-08-04T15:24:51Z"
    finalizers:
    - imageregistry.operator.openshift.io/finalizer
    generation: 1
    managedFields:
    - apiVersion: imageregistry.operator.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"imageregistry.operator.openshift.io/finalizer": {}
        f:spec:
          .: {}
          f:httpSecret: {}
          f:logging: {}
          f:managementState: {}
          f:proxy: {}
          f:replicas: {}
          f:requests:
            .: {}
            f:read:
              .: {}
              f:maxWaitInQueue: {}
            f:write:
              .: {}
              f:maxWaitInQueue: {}
          f:rolloutStrategy: {}
          f:storage: {}
        f:status:
          .: {}
          f:conditions: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:storage: {}
          f:storageManaged: {}
      manager: cluster-image-registry-operator
      operation: Update
      time: "2020-08-04T20:05:02Z"
    name: cluster
    resourceVersion: "125767"
    selfLink: /apis/imageregistry.operator.openshift.io/v1/configs/cluster
    uid: 44fe2096-b577-4181-a421-466e5f116df9
  spec:
    httpSecret: 84cf21baf3a47764c3ba35a4e4f80768a8d3601356b83d36544e415894af608615c29140a79f1a637f3b99639016237eabc2fedb8c190a09a8b8c95dff3df5eb
    logging: 2
    managementState: Removed
    proxy: {}
    replicas: 1
    requests:
      read:
        maxWaitInQueue: 0s
      write:
        maxWaitInQueue: 0s
    rolloutStrategy: RollingUpdate
    storage: {}
  status:
    conditions:
    - lastTransitionTime: "2020-08-04T15:24:55Z"
      reason: AsExpected
      status: "False"
      type: ImageConfigControllerDegraded
    - lastTransitionTime: "2020-08-04T15:24:55Z"
      reason: AsExpected
      status: "False"
      type: ImageRegistryCertificatesControllerDegraded
    - lastTransitionTime: "2020-08-04T15:24:58Z"
      reason: AsExpected
      status: "False"
      type: NodeCADaemonControllerDegraded
    - lastTransitionTime: "2020-08-04T20:05:02Z"
      message: All registry resources are removed
      reason: Removed
      status: "False"
      type: Progressing
    - lastTransitionTime: "2020-08-04T15:24:58Z"
      message: The registry is removed
      reason: Removed
      status: "True"
      type: Available
    - lastTransitionTime: "2020-08-04T15:24:58Z"
      message: The registry is removed
      reason: Removed
      status: "False"
      type: Degraded
    - lastTransitionTime: "2020-08-04T15:24:58Z"
      message: The registry is removed
      reason: Removed
      status: "True"
      type: Removed
    observedGeneration: 1
    readyReplicas: 0
    storage: {}
    storageManaged: false
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
