apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
  labels:
    bucket-provisioner: openshift-storage.ceph.rook.io-bucket
spec:
  bucketName: thanos-object-storage-bucket
  generateBucketName: thanos-object-storage
  objectBucketName: obc-open-cluster-management-observability-thanos-object-storage
  storageClassName: ocs-storagecluster-ceph-rgw
