apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: thanos-object-storage
      endpoint: rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc:80
      insecure: true
      access_key: 093MJFV854H3BSE095HJ
      secret_key: BUU0eF8m8VGs40wREq16SKcz1mBpqncLEDk6dUrx
