kind: Namespace
apiVersion: v1
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: acm-app-storage
---
kind: Namespace
apiVersion: v1
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: ggithubcom-h00pz-ocp-build-ns
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: baremetal-storage-localdisk
  namespace: acm-app-storage
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - baremetal-storage-localdisk
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  annotations:
    open-cluster-management.io/user-group: c3lzdGVtOmF1dGhlbnRpY2F0ZWQ6b2F1dGgsc3lzdGVtOmF1dGhlbnRpY2F0ZWQ=
    open-cluster-management.io/user-identity: bWhAaDAwcHouY28=
  labels:
    app: baremetal-storage-localdisk
  name: baremetal-storage-localdisk-placement-0
  namespace: acm-app-storage
spec:
  clusterSelector:
    matchLabels:
      local-cluster: 'true'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: baremetal-storage-localdisk-subscription-0
  namespace: acm-app-storage
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: storage/local-storage/
  labels:
    app: baremetal-storage-localdisk
spec:
  channel: ggithubcom-h00pz-ocp-build-ns/ggithubcom-h00pz-ocp-build
  placement:
    placementRef:
      name: baremetal-storage-localdisk-placement-0
      kind: PlacementRule
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    open-cluster-management.io/user-group: c3lzdGVtOmF1dGhlbnRpY2F0ZWQ6b2F1dGgsc3lzdGVtOmF1dGhlbnRpY2F0ZWQ=
    open-cluster-management.io/user-identity: bWhAaDAwcHouY28=
  name: ggithubcom-h00pz-ocp-build
  namespace: ggithubcom-h00pz-ocp-build-ns
spec:
  pathname: 'https://github.com/h00pz/ocp-build.git'
  type: Git
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: baremetal-storage-localdisk-placement-0
  namespace: acm-app-storage
  annotations: {}
  labels:
    app: baremetal-storage-localdisk
  selfLink: /apis/apps.open-cluster-management.io/v1/namespaces/acm-app-storage/placementrules/baremetal-storage-localdisk-placement-0
spec:
  clusterSelector:
    matchLabels:
      local-cluster: 'true'
