apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
  namespace: open-cluster-management
spec:
  availabilityConfig: basic
  imagePullPolicy: Always
  imagePullSecret: multiclusterhub-operator-pull-secret
  observabilityAddonSpec:
    enableMetrics: true
    interval: 30
  retentionResolution1h: 30d
  retentionResolution5m: 14d
  retentionResolutionRaw: 5d
  storageConfigObject:
    metricObjectStorage:
      key: thanos.yaml
      name: thanos-object-storage
    statefulSetSize: 50Gi
    statefulSetStorageClass: thin
