kind: Namespace
apiVersion: v1
metadata:
  name: argocd
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: argocd
  namespace: argocd
spec:
  targetNamespaces:
    - argocd
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "argocd-operator"
  namespace: "argocd"
  olm.operatorGroup: argocd
spec:
  channel: "alpha"
  installPlanApproval: "Automatic"
  source: "community-operators"
  sourceNamespace: "openshift-marketplace"
  name: "argocd-operator"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "prometheus"
  namespace: "argocd"
  olm.operatorGroup: argocd
spec:
  channel: "beta"
  installPlanApproval: "Automatic"
  source: "community-operators"
  sourceNamespace: "openshift-marketplace"
  name: "prometheus"
---
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: argocd-users
users: null
---
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: argocd-admins
users:
  - mh@h00pz.co
---
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: devteam1
users:
  - developer1
  - developer2
