#!/bin/bash
cd /root/c2
rm -rf /root/c2/*.ign
cd /root/c2
scp root@172.30.26.10:/var/www/html/*.ign /root/c2
cd /root/c2
oc delete secret generic master-ign -n openshift-cnv
oc delete secret generic worker-ign -n openshift-cnv
oc delete secret generic bootstrap-ign -n openshift-cnv
oc create secret generic master-ign --from-file=userdata="master.ign" -n openshift-cnv
oc create secret generic worker-ign --from-file=userdata="worker.ign" -n openshift-cnv
oc create secret generic bootstrap-ign --from-file=userdata="bootstrap.ign" -n openshift-cnv
