apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1alpha3
    kubevirt.io/storage-observed-api-version: v1alpha3
    kubevirt.ui/firstBoot: 'false'
    kubevirt.ui/pxeInterface: nic-0
    name.os.template.kubevirt.io/rhel8.2: Red Hat Enterprise Linux 8.0 or higher
  name: master2-c2
  namespace: openshift-cnv
  labels:
    app: master2-c2
    os.template.kubevirt.io/rhel8.2: 'true'
    vm.kubevirt.io/template: rhel8-server-large-v0.10.0
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.11.2
    workload.template.kubevirt.io/server: 'true'
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1alpha1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: master2-c2-disk-0
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
          storageClassName: ocs-storagecluster-ceph-rbd
          volumeMode: Filesystem
        source:
          http:
            url: 'http://172.30.23.27/vms/rhcos-452-osp.qcow2'
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: master2-c2
        kubevirt.io/size: large
        os.template.kubevirt.io/rhel8.2: 'true'
        vm.kubevirt.io/name: master2-c2
        workload.template.kubevirt.io/server: 'true'
    spec:
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        devices:
          autoattachPodInterface: false
          disks:
            - disk:
                bus: virtio
              name: disk-0
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - bridge: {}
              macAddress: '52:54:00:e0:27:a4'
              model: virtio
              name: nic-0
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: pc-q35-rhel8.2.0
        resources:
          requests:
            memory: 16Gi
      evictionStrategy: LiveMigrate
      hostname: master2-c2
      networks:
        - multus:
            networkName: nad-vlan26
          name: nic-0
      terminationGracePeriodSeconds: 0
      volumes:
        - dataVolume:
            name: master2-c2-disk-0
          name: disk-0
        - cloudInitConfigDrive:
            secretRef:
              name: master-ign
          name: cloudinitdisk
