apiVersion: compliance.openshift.io/v1alpha1
kind: ComplianceRemediation
metadata:
  creationTimestamp: "2021-03-10T16:00:13Z"
  generation: 3
  labels:
    compliance.openshift.io/scan-name: rhcos4-moderate-master
    compliance.openshift.io/suite: nist-moderate
  managedFields:
  - apiVersion: compliance.openshift.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:compliance.openshift.io/scan-name: {}
          f:compliance.openshift.io/suite: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"e696353a-c1c8-400e-baf0-dce04efe0070"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        .: {}
        f:current:
          .: {}
          f:object:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:spec:
              .: {}
              f:config:
                .: {}
                f:ignition:
                  .: {}
                  f:version: {}
              f:kernelArguments: {}
        f:outdated: {}
      f:status:
        .: {}
        f:applicationState: {}
    manager: compliance-operator
    operation: Update
    time: "2021-03-10T22:02:26Z"
  - apiVersion: compliance.openshift.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:apply: {}
    manager: oc
    operation: Update
    time: "2021-03-10T22:02:26Z"
  name: rhcos4-moderate-master-coreos-pti-kernel-argument
  namespace: openshift-compliance
  ownerReferences:
  - apiVersion: compliance.openshift.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ComplianceCheckResult
    name: rhcos4-moderate-master-coreos-pti-kernel-argument
    uid: e696353a-c1c8-400e-baf0-dce04efe0070
  resourceVersion: "1000209"
  selfLink: /apis/compliance.openshift.io/v1alpha1/namespaces/openshift-compliance/complianceremediations/rhcos4-moderate-master-coreos-pti-kernel-argument
  uid: 813dfdab-b875-4e88-b287-6fcf7126d4ec
spec:
  apply: false
  current:
    object:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      spec:
        config:
          ignition:
            version: 3.1.0
        kernelArguments:
        - pti=on
  outdated: {}
status:
  applicationState: NotApplied
