apiVersion: compliance.openshift.io/v1alpha1
kind: ComplianceRemediation
metadata:
  creationTimestamp: "2021-03-10T16:00:29Z"
  generation: 3
  labels:
    compliance.openshift.io/scan-name: rhcos4-moderate-master
    compliance.openshift.io/suite: nist-moderate
  managedFields:
  - apiVersion: compliance.openshift.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:compliance.openshift.io/scan-name: {}
          f:compliance.openshift.io/suite: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"9cd1ad23-5496-421b-b0f6-9934e06323f0"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        .: {}
        f:current:
          .: {}
          f:object:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:spec:
              .: {}
              f:config:
                .: {}
                f:ignition:
                  .: {}
                  f:version: {}
                f:storage:
                  .: {}
                  f:files: {}
        f:outdated: {}
      f:status:
        .: {}
        f:applicationState: {}
    manager: compliance-operator
    operation: Update
    time: "2021-03-10T22:02:33Z"
  - apiVersion: compliance.openshift.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:apply: {}
    manager: oc
    operation: Update
    time: "2021-03-10T22:02:33Z"
  name: rhcos4-moderate-master-sysctl-net-ipv4-conf-all-log-martians
  namespace: openshift-compliance
  ownerReferences:
  - apiVersion: compliance.openshift.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ComplianceCheckResult
    name: rhcos4-moderate-master-sysctl-net-ipv4-conf-all-log-martians
    uid: 9cd1ad23-5496-421b-b0f6-9934e06323f0
  resourceVersion: "1000421"
  selfLink: /apis/compliance.openshift.io/v1alpha1/namespaces/openshift-compliance/complianceremediations/rhcos4-moderate-master-sysctl-net-ipv4-conf-all-log-martians
  uid: 5bd3f7ac-a70e-462e-a28c-0647ca7f0b4e
spec:
  apply: false
  current:
    object:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      spec:
        config:
          ignition:
            version: 3.1.0
          storage:
            files:
            - contents:
                source: data:,net.ipv4.conf.all.log_martians%3D1%0A
              mode: 420
              overwrite: true
              path: /etc/sysctl.d/75-sysctl_net_ipv4_conf_all_log_martians.conf
  outdated: {}
status:
  applicationState: NotApplied
