apiVersion: compliance.openshift.io/v1alpha1
kind: ComplianceRemediation
metadata:
  creationTimestamp: "2021-03-10T16:00:13Z"
  generation: 3
  labels:
    compliance.openshift.io/scan-name: rhcos4-moderate-master
    compliance.openshift.io/suite: nist-moderate
  managedFields:
  - apiVersion: compliance.openshift.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:compliance.openshift.io/scan-name: {}
          f:compliance.openshift.io/suite: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"87e7811d-7dcf-4ba2-8cb7-432feb5aa26f"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        .: {}
        f:current:
          .: {}
          f:object:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:spec:
              .: {}
              f:config:
                .: {}
                f:ignition:
                  .: {}
                  f:version: {}
                f:storage:
                  .: {}
                  f:files: {}
        f:outdated: {}
      f:status:
        .: {}
        f:applicationState: {}
    manager: compliance-operator
    operation: Update
    time: "2021-03-10T22:02:27Z"
  - apiVersion: compliance.openshift.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:apply: {}
    manager: oc
    operation: Update
    time: "2021-03-10T22:02:27Z"
  name: rhcos4-moderate-master-disable-users-coredumps
  namespace: openshift-compliance
  ownerReferences:
  - apiVersion: compliance.openshift.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ComplianceCheckResult
    name: rhcos4-moderate-master-disable-users-coredumps
    uid: 87e7811d-7dcf-4ba2-8cb7-432feb5aa26f
  resourceVersion: "1000230"
  selfLink: /apis/compliance.openshift.io/v1alpha1/namespaces/openshift-compliance/complianceremediations/rhcos4-moderate-master-disable-users-coredumps
  uid: fa52b3f5-1c42-4bf5-ae8b-bf3610de3ac3
spec:
  apply: false
  current:
    object:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      spec:
        config:
          ignition:
            version: 3.1.0
          storage:
            files:
            - contents:
                source: data:,%2A%20%20%20%20%20hard%20%20%20core%20%20%20%200
              mode: 420
              overwrite: true
              path: /etc/security/limits.d/75-disable_users_coredumps.conf
  outdated: {}
status:
  applicationState: NotApplied
