apiVersion: compliance.openshift.io/v1alpha1
kind: ComplianceRemediation
metadata:
  creationTimestamp: "2021-03-10T16:00:08Z"
  generation: 3
  labels:
    compliance.openshift.io/scan-name: rhcos4-moderate-master
    compliance.openshift.io/suite: nist-moderate
  managedFields:
  - apiVersion: compliance.openshift.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:compliance.openshift.io/scan-name: {}
          f:compliance.openshift.io/suite: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"b31ee1a1-89ac-4ae8-96f8-76972143ecec"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        .: {}
        f:current:
          .: {}
          f:object:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:spec:
              .: {}
              f:config:
                .: {}
                f:ignition:
                  .: {}
                  f:version: {}
                f:storage:
                  .: {}
                  f:files: {}
        f:outdated: {}
      f:status:
        .: {}
        f:applicationState: {}
    manager: compliance-operator
    operation: Update
    time: "2021-03-10T22:02:27Z"
  - apiVersion: compliance.openshift.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:apply: {}
    manager: oc
    operation: Update
    time: "2021-03-10T22:02:27Z"
  name: rhcos4-moderate-master-disable-ctrlaltdel-burstaction
  namespace: openshift-compliance
  ownerReferences:
  - apiVersion: compliance.openshift.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ComplianceCheckResult
    name: rhcos4-moderate-master-disable-ctrlaltdel-burstaction
    uid: b31ee1a1-89ac-4ae8-96f8-76972143ecec
  resourceVersion: "1000226"
  selfLink: /apis/compliance.openshift.io/v1alpha1/namespaces/openshift-compliance/complianceremediations/rhcos4-moderate-master-disable-ctrlaltdel-burstaction
  uid: 4c162e65-8d2e-4a02-8c7f-6bdd047d3460
spec:
  apply: false
  current:
    object:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      spec:
        config:
          ignition:
            version: 3.1.0
          storage:
            files:
            - contents:
                source: data:,CtrlAltDelBurstAction%3Dnone
              mode: 420
              overwrite: true
              path: /etc/systemd/system.conf.d/disable_ctrlaltdelete_burstaction.conf
  outdated: {}
status:
  applicationState: NotApplied
