---
- name: Make sure the temp directory exists
  file:
    path: "{{ temp_folder }}"
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"

- name: Copy ACM files to temp_folder
  copy:
    src: "{{ item }}"
    dest: "{{ temp_folder }}"
    mode: 0644
  with_items:
    - 1_acm_ns.yaml
    - 2_acm_og.yaml
    - 3_acm_sub.yaml
    - 4_acm_multi_cluster_hub.yaml

- name: Create ACM Namespace
  command: oc create -f {{ temp_folder }}/1_argo_env.yaml

- name: Create ACM Operators Group
  command: oc create -f {{ temp_folder }}/2_acm_og.yaml

- name: Setup ACM Subscription
  command: oc apply -f {{ temp_folder }}/3_acm_sub.yaml

- name: Setup ACM Multi Cluster Hub
  command: oc apply -f {{ temp_folder }}/4_multi_cluster_hub.yaml
