apiVersion: apps/v1
kind: Deployment
metadata:
  name: crocodile-api
  namespace: crocs
  labels:
    app: crocodile-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crocodile-api
  template:
    metadata:
      labels:
        app: crocodile-api
    spec:
      containers:
        - name: crocodile
          image: voodoodror/crocodile-api
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
---
kind: Service
apiVersion: v1
metadata:
  name: crocodile-service
  namespace: crocs
spec:
  type: ClusterIP
  selector:
    app: crocodile-api
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: crocs
