apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: crocodile-api
  name: crocs-monitor
  namespace: crocs
spec:
  endpoints:
  - interval: 30s
    port: crocs
    scheme: http
    path: /metrics
  selector:
    matchLabels:
      app: crocodile-api
