kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hub1-redis-data
  namespace: ansible-automation-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi
  volumeMode: Filesystem
