kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hub1-file-storage
  namespace: ansible-automation-platform
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
