kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ansible-projects-pvc
  namespace: ansible-automation-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
