apiVersion: automationhub.ansible.com/v1beta1
kind: AutomationHub
metadata:
  name: hub1
  namespace: ansible-automation-platform
spec:
  route_tls_termination_mechanism: Edge
  ingress_type: Route
  loadbalancer_port: 80
  admin_password_secret: tower-admin-password
  file_storage_size: 100Gi
  image_pull_policy: IfNotPresent
  file_storage_storage_class: thin
  web:
    replicas: 1
  file_storage_access_mode: ReadWriteMany
  content:
    log_level: INFO
    replicas: 1
  api:
    log_level: INFO
    replicas: 1
  loadbalancer_protocol: http
  resource_manager:
    replicas: 1
  storage_type: File
  worker:
    replicas: 1
